[package]
name = "frontend"
version = "0.1.0"
authors = ["Martin Tang <martin.tang365@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seed = "0.7.0"

[lib]
crate-type = ["cdylib", "rlib"]